"use client";
import Image from "next/image";
import { useMemo, useState, useEffect } from "react";
import { motion } from "framer-motion";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { ArrowRight, Camera, Check, ChevronDown, CircleCheck, CreditCard, Heart, Menu, Minus, PackageCheck, Plus, Search, ShieldCheck, ShoppingBag, SlidersHorizontal, Trash2, Truck, UserRound } from "lucide-react";
import { Accordion,AccordionContent,AccordionItem,AccordionTrigger } from "@/components/ui/accordion";
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet";
import { Drawer,DrawerContent,DrawerDescription,DrawerHeader,DrawerTitle,DrawerTrigger } from "@/components/ui/drawer";
import { Toaster } from "@/components/ui/sonner";
import { categories,getProduct,money,products,type Product } from "@/lib/catalog";
import { useCommerceStore } from "@/store/commerce-store";

export function ProductVisual({cell,name,priority=false}: {cell:number;name:string;priority?:boolean}) { const col=cell%4,row=Math.floor(cell/4); return <div className="product-crop"><Image src="/images/product-sheet.png" alt={name} width={1456} height={1092} priority={priority} style={{left:`${-col*100}%`,top:`${-row*100}%`}}/></div> }
function EditorialVisual({cell,label}: {cell:number;label:string}) { const col=cell%3,row=Math.floor(cell/3); return <div className="editorial-crop"><Image src="/images/editorial-sheet.png" alt={label} width={1536} height={1024} style={{left:`${-col*100}%`,top:`${-row*100}%`}}/></div> }

function AddButton({product,label="Add to bag"}:{product:Product;label?:string}) { const add=useCommerceStore(s=>s.add); return <button className="button button-dark" disabled={!product.stock} onClick={()=>{add(product.slug);toast.success(`${product.name} added to your bag`)}}>{product.stock?label:"Unavailable"}</button> }
function WishButton({product}:{product:Product}) { const {wishlist,toggleWishlist}=useCommerceStore(); const active=wishlist.includes(product.slug); return <button className={`wish-button ${active?"active":""}`} aria-label={`${active?"Remove":"Save"} ${product.name}`} aria-pressed={active} onClick={()=>{toggleWishlist(product.slug);toast(active?"Removed from wishlist":"Saved to wishlist")}}><Heart fill={active?"currentColor":"none"}/></button> }
function ProductCard({product,index=0}:{product:Product;index?:number}) { return <motion.article className="product-card" initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:Math.min(index*.035,.2)}}>{product.badge&&<span className="product-badge">{product.badge}</span>}<a href={`/product/${product.slug}`}><ProductVisual cell={product.cell} name={product.name} priority={index<2}/></a><WishButton product={product}/><div className="product-info"><div><h3><a href={`/product/${product.slug}`}>{product.name}</a></h3><p>{product.category}</p></div><p className="price">{money(product.price)} {product.compareAtPrice&&<del>{money(product.compareAtPrice)}</del>}</p></div><AddButton product={product} label="Quick add"/></motion.article> }

function Header(){ const [menu,setMenu]=useState(false); const cart=useCommerceStore(s=>s.cart); const setCartOpen=useCommerceStore(s=>s.setCartOpen); const count=cart.reduce((n,l)=>n+l.quantity,0); return <><p className="announcement">Free shipping on orders over ₹999 <span>Complimentary returns within 14 days</span></p><header className="site-header"><button className="icon-button mobile-only" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button><a className="wordmark" href="/">GALLERY</a><nav>{["New in","Women","Men","Bags","Jewelry","Accessories","Sale"].map(item=><a key={item} href={item==="Bags"?"/category/bags":"/shop"}>{item}</a>)}</nav><div className="header-actions"><a className="icon-button" href="/search" aria-label="Search"><Search/></a><a className="icon-button desktop-icon" href="/account" aria-label="Account"><UserRound/></a><a className="icon-button desktop-icon" href="/wishlist" aria-label="Wishlist"><Heart/></a><button className="icon-button cart-icon" onClick={()=>setCartOpen(true)} aria-label={`Cart with ${count} items`}><ShoppingBag/><span>{count}</span></button></div></header><Sheet open={menu} onOpenChange={setMenu}><SheetContent side="left" className="mobile-menu"><SheetHeader><SheetTitle>GALLERY</SheetTitle><SheetDescription>Explore the collection</SheetDescription></SheetHeader>{["New in","Women","Men","Bags","Jewelry","Accessories","Travel","Sale"].map((item,i)=><a key={item} href={item==="Travel"?"/category/travel":"/shop"}>{String(i+1).padStart(2,"0")}<span>{item}</span><ArrowRight/></a>)}</SheetContent></Sheet><CartDrawer/></> }
function Footer(){return <footer><div className="footer-brand"><a className="wordmark" href="/">GALLERY</a><p>Objects of character for modern everyday life.</p></div>{[["SHOP","New Arrivals","Women","Men","Bags","Jewelry","Sale"],["HELP","Contact","Shipping & Returns","FAQ","Track Order"],["ABOUT","Our Story","Journal","Stores","Careers"],["LEGAL","Privacy","Terms","Refund Policy"]].map(([title,...links])=><div key={title}><h3>{title}</h3>{links.map(link=><a key={link} href={link==="FAQ"?"/faq":link==="Journal"?"/journal":link==="Our Story"?"/about":link==="Contact"?"/contact":link==="Track Order"?"/track-order":"/shop"}>{link}</a>)}</div>)}<div className="footer-bottom"><span>GALLERY © 2026</span><span>INDIA · INR</span><span>VISA · UPI · MASTERCARD</span></div></footer>}
function Shell({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/><Toaster position="bottom-center" richColors/></>}

function Home(){return <Shell><section className="hero"><Image src="/images/gallery-hero.png" alt="GALLERY new season accessories campaign" fill priority sizes="100vw"/><div className="hero-shade"/><motion.div className="hero-copy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}><p className="eyebrow">New season 2026</p><h1>The details<br/>matter.</h1><div className="hero-actions"><a className="button button-light" href="/shop">Shop new arrivals</a><a className="text-link light" href="#collection">Explore collection <ArrowRight/></a></div></motion.div><p className="hero-index">Campaign 01 / 03</p></section><section className="category-intro section-shell"><div className="editorial-heading"><p className="eyebrow dark">The GALLERY edit</p><h2>Curated for everyday</h2><p>Thoughtfully selected accessories designed to complete the way you move, work and live.</p></div><div className="category-rail">{categories.map((c)=><a href={`/category/${c.slug}`} key={c.slug}><EditorialVisual cell={c.cell} label={`${c.label} collection`}/><span>{c.label}<ArrowRight/></span></a>)}</div></section><ProductSection title="New arrivals" subtitle="Fresh pieces. Quietly distinctive." items={products.slice(0,8)}/><section className="editorial-banner"><EditorialVisual cell={1} label="Woman wearing sculptural jewelry"/><div><p className="eyebrow">The jewelry edit</p><h2>Quiet forms,<br/>lasting presence.</h2><p>Pieces that add character without demanding attention.</p><a className="button button-light" href="/category/jewelry">Discover jewelry</a></div></section><ProductSection title="Best sellers" subtitle="The pieces you return to." items={products.filter((_,i)=>i%3===0).slice(0,4)}/><section className="brand-story section-shell"><div><EditorialVisual cell={5} label="Leather travel bag in a refined hotel"/></div><div><p className="eyebrow dark">Our point of view</p><h2>Made to complete the look</h2><p>Gallery brings together refined accessories designed for modern everyday life — pieces that add character without demanding attention.</p><a className="text-link" href="/about">Our story <ArrowRight/></a></div></section><section className="promo"><p className="eyebrow">The private edit</p><h2>Up to 30% off<br/>selected accessories</h2><a className="button button-light" href="/shop?sort=price-low">Shop sale</a></section><Social/><Newsletter/></Shell>}
function ProductSection({title,subtitle,items}:{title:string;subtitle:string;items:Product[]}){return <section id="collection" className="section-shell"><div className="section-heading"><div><p className="eyebrow dark">Curated selection</p><h2>{title}</h2></div><p>{subtitle}</p><a className="text-link" href="/shop">View all <ArrowRight/></a></div><div className="product-grid">{items.map((p,i)=><ProductCard product={p} index={i} key={p.slug}/>)}</div></section>}
function Social(){return <section className="social section-shell"><div className="section-heading"><div><p className="eyebrow dark">In good company</p><h2>@GALLERY</h2></div><p>Follow the everyday edit.</p></div><div className="social-grid">{[0,1,2,3,4,5].map(i=><a href="#" key={i}><EditorialVisual cell={i} label="Gallery social post"/><span><Camera/> View post</span></a>)}</div></section>}
const emailSchema=z.object({email:z.string().email("Enter a valid email")});
function Newsletter(){const {register,handleSubmit,formState:{errors},reset}=useForm<{email:string}>({resolver:zodResolver(emailSchema)});return <section className="newsletter"><div><p className="eyebrow">Private notes</p><h2>Stay in the loop</h2><p>Be the first to discover new collections, limited drops and private offers.</p></div><form onSubmit={handleSubmit(()=>{toast.success("Welcome to GALLERY");reset()})}><input aria-label="Email address" placeholder="Email address" {...register("email")}/><button type="submit">Join us <ArrowRight/></button>{errors.email&&<span role="alert">{errors.email.message}</span>}</form></section>}

function Shop({category}:{category?:string}){const [sort,setSort]=useState("featured");const [query,setQuery]=useState("");const list=useMemo(()=>{let result=category?products.filter(p=>p.category===category):products;if(query)result=result.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));if(sort==="price-low")result=[...result].sort((a,b)=>a.price-b.price);if(sort==="price-high")result=[...result].sort((a,b)=>b.price-a.price);if(sort==="newest")result=[...result].reverse();return result},[category,sort,query]);return <Shell><div className="page-hero compact"><p className="eyebrow dark">Home / Collection</p><h1>{category?category:"All accessories"}</h1><p>Considered objects for every part of the day.</p></div><div className="shop-tools"><span>{list.length} pieces</span><label className="shop-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search collection"/></label><Drawer><DrawerTrigger className="filter-trigger"><SlidersHorizontal/> Filters</DrawerTrigger><DrawerContent><DrawerHeader><DrawerTitle>Filter collection</DrawerTitle><DrawerDescription>Refine by category, material and availability.</DrawerDescription></DrawerHeader><Filters/></DrawerContent></Drawer><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="newest">Newest</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option></select></label></div><div className="plp section-shell"><aside><Filters/></aside><div>{list.length?<div className="product-grid">{list.map((p,i)=><ProductCard key={p.slug} product={p} index={i}/>)}</div>:<Empty title="No pieces found" copy="Try another search or clear your filters." href="/shop" action="View all pieces"/>}<button className="button load-more">Load more</button></div></div></Shell>}
function Filters(){return <div className="filters">{["Category","Price","Color","Size","Material","Availability","Rating"].map((item,i)=><details key={item} open={i===0}><summary>{item}<ChevronDown/></summary><div>{i===0?Object.keys(categories).slice(0,6).map((_,j)=><label key={j}><input type="checkbox"/> {categories[j]?.label}</label>):<><label><input type="checkbox"/> Featured</label><label><input type="checkbox"/> In stock</label></>}</div></details>)}</div>}

function ProductPage({slug}:{slug?:string}){const product=getProduct(slug);const [color,setColor]=useState(0);return <Shell><div className="breadcrumbs"><a href="/">Home</a> / <a href={`/category/${product.category}`}>{product.category}</a> / {product.name}</div><main className="pdp"><div className="pdp-gallery"><ProductVisual cell={product.cell} name={product.name}/><ProductVisual cell={(product.cell+1)%12} name={`${product.name} detail`}/><span>1 / 2</span></div><div className="pdp-info"><p className="eyebrow dark">{product.category}</p><h1>{product.name}</h1><p className="rating">★★★★★ <span>{product.rating.toFixed(1)} · {product.reviewCount} reviews</span></p><p className="pdp-price">{money(product.price)} {product.compareAtPrice&&<><del>{money(product.compareAtPrice)}</del><span>Save {Math.round((1-product.price/product.compareAtPrice)*100)}%</span></>}</p><p>{product.description}</p><fieldset><legend>Color — {color===0?"Black":color===1?"Forest":"Camel"}</legend><div className="swatches">{product.colors.map((c,i)=><button key={c} className={color===i?"selected":""} style={{background:c}} onClick={()=>setColor(i)} aria-label={`Color ${i+1}`}/>)}</div></fieldset><div className="pdp-actions"><AddButton product={product}/><a className="button" href="/checkout">Buy now</a><WishButton product={product}/></div><div className="trust-row"><span><ShieldCheck/>Secure checkout</span><span><PackageCheck/>Easy returns</span><span><Truck/>Fast delivery</span></div><Accordion type="single" collapsible>{[["description","Description",product.description],["materials","Materials",product.material],["dimensions","Dimensions","Designed with balanced proportions for everyday use."],["shipping","Shipping","Complimentary shipping over ₹999. Dispatches in 1–2 business days."],["returns","Returns","Easy returns within 14 days of delivery."],["care","Care","Store in the provided dust bag and keep away from moisture."]].map(([v,t,c])=><AccordionItem value={v} key={v}><AccordionTrigger>{t}</AccordionTrigger><AccordionContent>{c}</AccordionContent></AccordionItem>)}</Accordion></div></main><ProductSection title="You may also like" subtitle="Selected to complete the look." items={products.filter(p=>p.category===product.category&&p.slug!==product.slug).slice(0,4)}/></Shell>}

function CartDrawer(){const {cart,cartOpen,setCartOpen,remove,setQuantity}=useCommerceStore();const lines=cart.map(l=>({...l,product:getProduct(l.slug)}));const subtotal=lines.reduce((n,l)=>n+l.product.price*l.quantity,0);return <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-drawer"><SheetHeader><SheetTitle>Your bag ({cart.length})</SheetTitle><SheetDescription>{subtotal<999?`${money(999-subtotal)} away from free shipping`:"You have unlocked free shipping"}</SheetDescription></SheetHeader><div className="shipping-progress"><span style={{width:`${Math.min(subtotal/999*100,100)}%`}}/></div><div className="cart-lines">{lines.length?lines.map(l=><div className="cart-line" key={l.slug}><ProductVisual cell={l.product.cell} name={l.product.name}/><div><h3>{l.product.name}</h3><p>{money(l.product.price)}</p><div className="quantity"><button onClick={()=>setQuantity(l.slug,l.quantity-1)}><Minus/></button><span>{l.quantity}</span><button onClick={()=>setQuantity(l.slug,l.quantity+1)}><Plus/></button></div></div><button onClick={()=>remove(l.slug)} aria-label={`Remove ${l.product.name}`}><Trash2/></button></div>):<Empty title="Your bag is empty" copy="A considered selection is waiting." href="/shop" action="Explore collection"/>}</div>{lines.length>0&&<div className="cart-footer"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><a className="button" href="/cart">View cart</a><a className="button button-dark" href="/checkout">Checkout</a></div>}</SheetContent></Sheet>}
function CartPage(){const {cart,remove,setQuantity}=useCommerceStore();const lines=cart.map(l=>({...l,product:getProduct(l.slug)}));const subtotal=lines.reduce((n,l)=>n+l.product.price*l.quantity,0);return <Shell><div className="page-hero compact"><p className="eyebrow dark">Your selection</p><h1>Shopping bag</h1></div>{lines.length?<main className="cart-page"><div className="cart-lines">{lines.map(l=><div className="cart-line large" key={l.slug}><ProductVisual cell={l.product.cell} name={l.product.name}/><div><h3>{l.product.name}</h3><p>{l.product.category} · {l.product.material}</p><strong>{money(l.product.price)}</strong><div className="quantity"><button onClick={()=>setQuantity(l.slug,l.quantity-1)}><Minus/></button><span>{l.quantity}</span><button onClick={()=>setQuantity(l.slug,l.quantity+1)}><Plus/></button></div></div><button onClick={()=>remove(l.slug)}><Trash2/></button></div>)}</div><OrderSummary subtotal={subtotal}/></main>:<Empty title="Your bag is empty" copy="Explore our newest accessories and find something made for your everyday." href="/shop" action="Explore collection"/>}</Shell>}
function OrderSummary({subtotal}:{subtotal:number}){return <aside className="order-summary"><h2>Order summary</h2><p><span>Subtotal</span><strong>{money(subtotal)}</strong></p><p><span>Shipping</span><strong>{subtotal>=999?"Complimentary":money(149)}</strong></p><p className="order-total"><span>Total</span><strong>{money(subtotal+(subtotal>=999?0:149))}</strong></p><a className="button button-dark" href="/checkout">Proceed to checkout</a><small>Secure checkout · Easy returns</small></aside>}

const checkoutSchema=z.object({email:z.string().email(),phone:z.string().min(10),name:z.string().min(2),address:z.string().min(8),city:z.string().min(2),state:z.string().min(2),postal:z.string().min(6),payment:z.string()});
type CheckoutData=z.infer<typeof checkoutSchema>;
function Checkout(){const cart=useCommerceStore(s=>s.cart),clearCart=useCommerceStore(s=>s.clearCart);const subtotal=cart.reduce((n,l)=>n+getProduct(l.slug).price*l.quantity,0);const {register,handleSubmit,formState:{errors}}=useForm<CheckoutData>({resolver:zodResolver(checkoutSchema),defaultValues:{payment:"upi"}});return <main className="checkout"><a className="wordmark" href="/">GALLERY</a><div className="checkout-grid"><form onSubmit={handleSubmit(()=>{clearCart();window.location.href="/order-success"})}><p className="eyebrow dark">Secure checkout</p><h1>Delivery details</h1><div className="step-row"><span className="active">1 Contact</span><span>2 Delivery</span><span>3 Payment</span><span>4 Review</span></div>{[["email","Email","email"],["phone","Phone","tel"],["name","Full name","text"],["address","Address","text"],["city","City","text"],["state","State","text"],["postal","Postal code","text"]].map(([name,label,type])=><label key={name}>{label}<input type={type} {...register(name as keyof CheckoutData)}/>{errors[name as keyof CheckoutData]&&<small>Please enter a valid {label.toLowerCase()}.</small>}</label>)}<fieldset><legend>Payment</legend>{[["card","Card"],["upi","UPI"],["cod","Cash on delivery"]].map(([v,l])=><label className="payment" key={v}><input type="radio" value={v} {...register("payment")}/><CreditCard/>{l}</label>)}</fieldset><button className="button button-dark" type="submit">Place order</button></form><OrderSummary subtotal={subtotal}/></div></main>}
function Success(){return <Shell><main className="success"><CircleCheck/><p className="eyebrow dark">Thank you</p><h1>Order confirmed</h1><p>Your order <strong>#GLR-26091</strong> is being prepared. Estimated delivery: 30 Sep–2 Oct.</p><div><a className="button button-dark" href="/track-order">Track order</a><a className="button" href="/shop">Continue shopping</a></div></main></Shell>}

function Wishlist(){const wishlist=useCommerceStore(s=>s.wishlist);const list=products.filter(p=>wishlist.includes(p.slug));return <Shell><div className="page-hero compact"><p className="eyebrow dark">Saved for later</p><h1>Wishlist</h1></div><div className="section-shell">{list.length?<div className="product-grid">{list.map((p,i)=><ProductCard product={p} index={i} key={p.slug}/>)}</div>:<Empty title="Your wishlist is empty" copy="Save the pieces you want to return to." href="/shop" action="Explore collection"/>}</div></Shell>}
function SearchPage(){const [q,setQ]=useState("");const list=q?products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())):products.slice(0,8);return <Shell><main className="search-page"><p className="eyebrow dark">Find your piece</p><label><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search bags, watches, jewelry..."/></label><div className="search-meta"><span>{list.length} results</span><span>Popular: Bags · Jewelry · Travel</span></div>{list.length?<div className="product-grid">{list.map((p,i)=><ProductCard product={p} index={i} key={p.slug}/>)}</div>:<Empty title="No pieces found" copy="Try a broader term such as bags, gold or leather." href="/shop" action="Browse all"/>}</main></Shell>}
function Empty({title,copy,href,action}:{title:string;copy:string;href:string;action:string}){return <div className="empty-state"><ShoppingBag/><h2>{title}</h2><p>{copy}</p><a className="button button-dark" href={href}>{action}</a></div>}

function Journal(){const stories=["The art of finishing well","A guide to everyday leather","Objects for the weekend","The quiet return of gold","How to choose a frame","Inside the travel edit"];return <Shell><div className="page-hero"><p className="eyebrow dark">Notes on style and objects</p><h1>Journal</h1></div><main className="journal-grid">{stories.map((s,i)=><article key={s}><EditorialVisual cell={i} label={s}/><p className="eyebrow dark">{["Style","Guides","Travel"][i%3]}</p><h2>{s}</h2><p>Thoughtful observations on design, material and the details that shape everyday style.</p><a className="text-link" href={`/journal/${s.toLowerCase().replaceAll(" ","-")}`}>Read story <ArrowRight/></a></article>)}</main></Shell>}
function StoryPage({kind="about"}:{kind?:string}){const content:{[k:string]:[string,string]}={about:["Our story","We believe the most useful objects can also be the most expressive. GALLERY brings together refined accessories, honest materials and a point of view shaped by modern life."],contact:["Let’s talk","Our client care team is here Monday to Saturday, 10:00–18:00 IST."],"shipping-returns":["Shipping & returns","Clear timelines, careful delivery and easy returns within 14 days."],faq:["Frequently asked questions","Everything you need to know about orders, delivery, returns and care."]};const [title,copy]=content[kind]??["The art of finishing well","Style is often decided in the final detail — the piece that makes an outfit feel complete."];return <Shell><main className="story-page"><div><p className="eyebrow dark">GALLERY / {kind.replaceAll("-"," ")}</p><h1>{title}</h1><p>{copy}</p>{kind==="contact"&&<form onSubmit={e=>{e.preventDefault();toast.success("Message received")}}><input required placeholder="Name"/><input required type="email" placeholder="Email"/><input required placeholder="Subject"/><textarea required placeholder="Message"/><button className="button button-dark">Send message</button></form>}</div><EditorialVisual cell={kind==="about"?0:4} label={title}/><Accordion type="single" collapsible>{["Orders","Shipping","Returns","Payments","Products","Account"].map(x=><AccordionItem value={x} key={x}><AccordionTrigger>{x}</AccordionTrigger><AccordionContent>We keep this simple: clear updates, careful handling and support whenever you need it.</AccordionContent></AccordionItem>)}</Accordion></main></Shell>}
function Auth({signup=false}:{signup?:boolean}){return <Shell><main className="auth-page"><form onSubmit={e=>{e.preventDefault();toast.success(signup?"Account created":"Welcome back")}}><p className="eyebrow dark">Your GALLERY</p><h1>{signup?"Create account":"Welcome back"}</h1>{signup&&<div className="split"><input required placeholder="First name"/><input required placeholder="Last name"/></div>}<input required type="email" placeholder="Email"/>{signup&&<input required type="tel" placeholder="Phone"/>}<input required type="password" placeholder="Password"/>{signup&&<input required type="password" placeholder="Confirm password"/>}<button className="button button-dark">{signup?"Create account":"Login"}</button><a href={signup?"/login":"/signup"}>{signup?"Already have an account? Login":"New here? Create account"}</a></form></main></Shell>}
function Account(){return <Shell><main className="account"><aside>{["Overview","Orders","Wishlist","Addresses","Profile","Settings"].map(x=><a href={x==="Wishlist"?"/wishlist":x==="Orders"?"/account/orders":"/account"} key={x}>{x}</a>)}</aside><div><p className="eyebrow dark">My GALLERY</p><h1>Welcome back</h1><div className="account-cards">{[["Recent orders","1 active order"],["Wishlist","Saved pieces"],["Addresses","1 saved address"]].map(([a,b])=><article key={a}><h2>{a}</h2><p>{b}</p><a className="text-link" href="#">View <ArrowRight/></a></article>)}</div></div></main></Shell>}
function Track(){const [found,setFound]=useState(false);return <Shell><main className="track"><p className="eyebrow dark">Order status</p><h1>Track your order</h1><form onSubmit={e=>{e.preventDefault();setFound(true)}}><input required placeholder="Order number"/><input required placeholder="Email or phone"/><button className="button button-dark">Track order</button></form>{found&&<div className="timeline">{["Order placed","Confirmed","Packed","Shipped","Out for delivery","Delivered"].map((s,i)=><div className={i<3?"done":""} key={s}><span>{i<3?<Check/>:i+1}</span><p><strong>{s}</strong>{i<3&&<small>Completed</small>}</p></div>)}</div>}</main></Shell>}
function NotFound(){return <Shell><main className="success"><p className="eyebrow dark">404</p><h1>This page has moved.</h1><p>The piece you were looking for is no longer here.</p><a className="button button-dark" href="/shop">Back to shop</a></main></Shell>}

export default function Storefront({segments=[]}:{segments?:string[]}){useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,opts?:unknown)=>void}}).modelContext;if(!ctx?.registerTool)return;const ctrl=new AbortController();ctx.registerTool({name:"search_catalog",title:"Search GALLERY catalog",description:"Search products by name or category.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:{query:string})=>products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(input.query.toLowerCase())).slice(0,8).map(p=>({name:p.name,price:money(p.price),url:`/product/${p.slug}`}))},{signal:ctrl.signal});return()=>ctrl.abort()},[]);const [root,second]=segments;if(!root)return <Home/>;if(root==="shop"||root==="category")return <Shop category={root==="category"?second:undefined}/>;if(root==="product")return <ProductPage slug={second}/>;if(root==="cart")return <CartPage/>;if(root==="checkout")return <Checkout/>;if(root==="order-success")return <Success/>;if(root==="wishlist")return <Wishlist/>;if(root==="search")return <SearchPage/>;if(root==="journal")return second?<StoryPage kind="article"/>:<Journal/>;if(["about","contact","faq","shipping-returns"].includes(root))return <StoryPage kind={root}/>;if(root==="login"||root==="signup")return <Auth signup={root==="signup"}/>;if(root==="account")return <Account/>;if(root==="track-order")return <Track/>;return <NotFound/>}
